import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import CountButton from '@features/clickCount/components/CountButton';
import Button from '@components/elements/Button';
import styles from '@styles/Home.module.css';
import ErrorButton from '@features/alert/components/ErrorButton';
import Profile from '@features/Profile';

const inter = Inter({ subsets: ['latin'] });

const Home = (): JSX.Element => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <Button text="検索" />
      <Profile name="広岡伸之甫" age={24} />
      <ErrorButton text="アラート発生" />
      <CountButton />
    </main>
  </>
);
export default Home;
